
freebsd_instance:
  image: freebsd-12-1-release-amd64
  
env:
  - LXML=true
  - LXML=false
  
task:
  install_script: pkg install -y python3 py37-pip

build_script:
  - pip-3.7 install -r requirements.txt
  - pip-3.7 install -r requirements-dev.txt
  - if [ "$LXML" == "true" ]; then pip-3.7 install lxml; fi
  
script:
  - python-3.7 -m pytest
